name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd helloworldapplication
        mvn clean install

    - name: Print Directory Contents
      run: |
        ls -R
        ls -R helloworldapplication/target

    - name: Include target directory
      run: |
        mv helloworldapplication/target .

    - name: Build Docker Image
      run: |
        docker build -f helloworldapplication/Dockerfile -t aratimahe/helloworldapplication:latest .

        docker images

    - name: Docker Login to JFrog
      run: echo ${{ secrets.JF_PASSWORD }} | docker login -u ${{ secrets.JF_USER }} --password-stdin githubactionsjfrog.jfrog.io

    - name: Docker Tag
      run: docker tag aratimahe/helloworldapplication githubactionsjfrog.jfrog.io/myrepo/aratimahe/helloworldapplication:latest

    - name: Docker Push to JFrog
      run: docker push githubactionsjfrog.jfrog.io/myrepo/aratimahe/helloworldapplication:latest
