name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd helloworldapplication
        mvn clean install

    - name: Print Directory Contents
      run: |
        ls -R
        ls -R helloworldapplication/target

    - name: Include target directory
      run: |
        mv helloworldapplication/target .

    - name: Build Docker Image
      run: |
        docker build -f helloworldapplication/Dockerfile -t aratimahe/helloworldapplication:latest .

        docker images

    - name: Docker Tag
      run: |
        docker tag aratimahe/helloworldapplication githubactionsjfrog.jfrog.io/myrepo/aratimahe/helloworldapplication:latest

    - name: JFrog CLI Setup
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: '2.52.10'
        oidc-provider-name: ''
        oidc-audience: ''
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_USER: ${{ secrets.JF_USER }}
        JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
        JF_SERVER_ID: "SERVER"

    - name: JFrog CLI Ping
      run: jfrog rt ping --url=$JF_URL

    - name: Docker Login to JFrog Artifactory
      run: |
        docker login -u "${{ secrets.JF_USER }}" -p "${{ secrets.JF_PASSWORD }}" githubactionsjfrog.jfrog.io

    - name: Docker Push to JFrog
      run: |
        jfrog rt docker-push githubactionsjfrog.jfrog.io/myrepo/aratimahe/helloworldapplication:latest --url=$JF_URL
