name: Java CI CD pipeline with maven 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Print contents of helloworldapplication directory
      run: ls -R helloworldapplication

    - name: Build Maven project
      run: mvn -f helloworldapplication clean install

    - name: Print contents of target directory
      run: ls -R helloworldapplication/target

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        context: helloworldapplication
        dockerfile: Dockerfile
        image: aratimahe/helloworldapplication
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
