name: Java CI CD pipeline with maven 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Update to v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4  # Update to v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Clean Up Artifacts
      run: rm -rf target

    - name: Build with Maven
      run: mvn clean install

    - name: Show Target Directory
      run: ls -R target

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: aratimahe/helloworldapplication
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
