name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Force Add Target Folder
      run: |
        git add -f helloworldapplication/target/
        git commit -m "Force add target/ folder"

    - name: Build with Maven
      run: |
        cd helloworldapplication
        mvn clean install

    - name: Build Docker Image
      run: docker build -f helloworldapplication/Dockerfile -t aratimahe/helloworldapplication:latest .

    - name: Push Docker Image
      run: docker push aratimahe/helloworldapplication:latest
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
